# Paths [Mandatory absolute Path]
data_root=/home/rafiq/final_project/src/data

# Server Configuration
port=3490
thread_count=16
queue_size=50
backlog=10

# Timeouts (seconds)
initial_timeout=5
default_keepalive_timeout=30
max_keepalive_timeout=120
max_keepalive_requests=100
cgi_timeout=5

# Cache
cache_slots=1024
max_cache_bytes=67108864

# Logging (0=off, 1=on)
verbose=0